/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true,
    paths: {
        Ext: '.',
        'Ext.ux': 'http://extjs.cachefly.net/extjs-4.1.1-gpl/examples/ux/',
        'Ext.ux.upload': '/ux/upload/'
    }
});

Ext.application({

    requires: [
        'Ext.ux.upload.Button',
        'Ext.ux.upload.plugin.Window',
        'Ext.grid.*',
        'Ext.util.*',
        'Ext.state.*',
        'Ext.data.*'
    ],
    models: [
        'SubmitContent',
        'State',
        'Publication'
    ],
    stores: [
        'State',
        'Publication'
    ],
    autoCreateViewport: true,
    name: 'SubmitContent',
    controllers: [
        'Main'
    ]
});
