/*
 * File: app/view/AdvertisementWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.AdvertisementWindow', {
    extend: 'Ext.window.Window',

    width: 750,
    layout: {
        type: 'fit'
    },
    title: 'Advertisement',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'AdvertisementForm',
                    bodyPadding: 10,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'ui-silk ui-silk-disk',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Cancel',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick11,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            padding: '0px 0px 10px 0px',
                            layout: {
                                type: 'column'
                            },
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    columnWidth: 0.5,
                                    id: 'adform_column1',
                                    defaults: {
                                        padding: '5px 0px 0px 0px'
                                    },
                                    layout: {
                                        type: 'column'
                                    },
                                    labelAlign: 'right',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            name: 'client',
                                            fieldLabel: 'Client',
                                            displayField: 'name',
                                            store: 'ClientStore',
                                            valueField: 'id'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    columnWidth: 0.5,
                                    defaults: {
                                        padding: '5px 0px'
                                    },
                                    layout: {
                                        type: 'column'
                                    },
                                    combineLabels: false,
                                    labelAlign: 'right',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            name: 'ad_type_id',
                                            fieldLabel: 'Ad Type',
                                            store: 'AdvertisementStore'
                                        },
                                        {
                                            xtype: 'combobox',
                                            name: 'ad_size_id',
                                            fieldLabel: 'Ad Size',
                                            store: 'ActivityTypeStore'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            name: 'client_id'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            name: 'contract_id',
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick11: function(button, e, options) {
        console.log(button);
    }

});