/*
 * File: app/view/ClientRecord.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NCPublishers.view.ClientRecord', {
    extend: 'Ext.form.Panel',
    alias: 'widget.clientrecord',
    requires: [
        'NCPublishers.view.RecordNavigation'
    ],

    bodyPadding: 5,
    title: 'Client Record',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: {
                anchor: '100%'
            },
            dockedItems: [
                {
                    xtype: 'recordnav',
                    itemId: 'RecordNavigation',
                    dock: 'top'
                }
            ],
            items: [
                {
                    xtype: 'container',
                    itemId: 'RecordHeader',
                    layout: {
                        padding: '0 0 25 0',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            border: 'false',
                            itemId: 'Column1',
                            defaultType: 'textfield',
                            layout: {
                                type: 'anchor'
                            },
                            flex: 1,
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Client Name',
                                    anchor: '95%'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Territory',
                                    anchor: '95%'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            border: 'false',
                            itemId: 'Column2',
                            layout: {
                                type: 'anchor'
                            },
                            flex: 1,
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Address Line 1',
                                    anchor: '100%'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'City',
                                    anchor: '100%'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    height: 350,
                    itemId: 'ClientSublists',
                    activeTab: 2,
                    plain: true,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'fit'
                            },
                            bodyPadding: 5,
                            title: 'General',
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    itemId: 'General-Sublists',
                                    activeTab: 3,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            title: 'Contacts'
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Activities'
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'User Notes'
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Files'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            autoScroll: false,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            bodyPadding: 5,
                            title: 'Sales',
                            items: [
                                {
                                    xtype: 'container',
                                    height: 50,
                                    itemId: 'SalesSublistHeader',
                                    maxHeight: 80,
                                    layout: {
                                        type: 'hbox'
                                    },
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'container',
                                            height: 94,
                                            itemId: 'Column1',
                                            width: 150,
                                            defaults: '{anchor: 95%}',
                                            layout: {
                                                type: 'anchor'
                                            },
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Label',
                                                    anchor: '95%'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Label',
                                                    anchor: '95%'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 72,
                                            itemId: 'Column2',
                                            width: 150,
                                            layout: {
                                                type: 'anchor'
                                            },
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Label',
                                                    anchor: '95%'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Label',
                                                    anchor: '95%'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tabpanel',
                                    itemId: 'SalesSublistTabs',
                                    width: 100,
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            title: 'Publications'
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Contracts'
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Advertisements'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            bodyPadding: 5,
                            title: 'Financial',
                            items: [
                                {
                                    xtype: 'container',
                                    height: 50,
                                    itemId: 'FinancialSublistHeader',
                                    layout: {
                                        align: 'stretch',
                                        padding: '',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    fieldLabel: 'Label',
                                                    boxLabel: 'Box Label'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    padding: '10 0',
                                    autoScroll: true,
                                    bodyBorder: false,
                                    preventHeader: true,
                                    title: 'PaymentsGrid',
                                    titleCollapse: true,
                                    flex: 1,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'String'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Number'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Date'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Boolean'
                                        }
                                    ],
                                    viewConfig: {

                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});