/*
 * File: app/view/ContractWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.ContractWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.contractwindow',

    height: 300,
    width: 750,
    layout: {
        type: 'fit'
    },
    title: 'Contract',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 204,
                    itemId: 'ContractForm',
                    bodyPadding: 5,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'ui-silk ui-silk-disk',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Cancel',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick1,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 3,
                                    layout: {
                                        type: 'anchor'
                                    },
                                    labelAlign: 'right',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '95%',
                                            fieldLabel: 'Contract Number',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '95%',
                                            fieldLabel: 'Client',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '95%',
                                            fieldLabel: 'Payment Type',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '95%',
                                            fieldLabel: 'Total Sales Amount',
                                            labelAlign: 'right',
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '95%',
                                            fieldLabel: 'Discount (%)',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '95%',
                                            fieldLabel: 'Design Fee',
                                            labelAlign: 'right'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    border: 1,
                                    width: 150,
                                    layout: {
                                        type: 'anchor'
                                    },
                                    combineLabels: false,
                                    labelAlign: 'right',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            anchor: '95%',
                                            fieldLabel: 'Subtotal',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '95%',
                                            fieldLabel: 'Total Amount',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '95%',
                                            fieldLabel: 'First Months Payment',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '95%',
                                            fieldLabel: 'Montly Payment',
                                            labelAlign: 'right'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick1: function(button, e, options) {
        console.log(button);
    }

});