/*
 * File: app/model/SubmitContent.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SubmitContent.model.SubmitContent', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'first_name'
        },
        {
            name: 'last_name'
        },
        {
            name: 'address1'
        },
        {
            name: 'address2'
        },
        {
            name: 'city'
        },
        {
            name: 'state_id'
        },
        {
            name: 'postal_code'
        },
        {
            name: 'email_address'
        },
        {
            name: 'phone_number'
        }
    ]
});