/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SubmitContent.controller.Main', {
    extend: 'Ext.app.Controller',

    views: [
        'SubmitContent',
        'ClassifiedContent',
        'OtherContent'
    ],

    refs: [
        {
            ref: 'contentForm',
            selector: 'contentForm'
        },
        {
            ref: 'classifiedPanel',
            selector: 'classifiedpanel'
        },
        {
            ref: 'otherContentPanel',
            selector: 'othercontentpanel'
        }
    ],

    onRadiofieldChange: function(field, newValue, oldValue, options) {
        if(field.itemId == "classifieds"){

            if(newValue){
                this.getContentForm().remove(me.otherPanel);
                this.getContentForm().add(me.classifiedPanel);
            } 

            this.getContentForm().doLayout();    
        } else if(field.itemId == "other_content"){


            if(newValue){
                this.getContentForm().remove(me.classifiedPanel);
                this.getContentForm().add(me.otherPanel);
            }

            this.getContentForm().doLayout();
        }
    },

    onLaunch: function() {
        var form = Ext.getCmp('contentForm').form;
        form.findField('phone_number').vtype="phoneNumber";
    },

    init: function(application) {
        me = this;
        me.classifiedPanel = new SubmitContent.view.ClassifiedContent();
        me.otherPanel = new SubmitContent.view.OtherContent();

        this.control({
            "radiofield": {
                change: this.onRadiofieldChange
            }
        });
    }

});
