/*
 * File: app/view/ClassifiedContent.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SubmitContent.view.ClassifiedContent', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.classifiedContent',

    itemId: 'classifiedpanel',
    margin: 0,
    autoScroll: true,
    autoDestroy: false,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    suspendLayout: true,
    bodyPadding: 0,
    title: 'Classified Ads & Job Postings',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: {
                labelAlign: 'top',
                padding: 10
            },
            items: [
                {
                    xtype: 'combobox',
                    flex: 1,
                    itemId: 'class_publication_id',
                    fieldLabel: 'Choose Your Publication',
                    labelStyle: 'font-weight:bold',
                    emptyText: 'Select a Publication...'
                },
                {
                    xtype: 'label',
                    flex: 1,
                    margin: '0 10',
                    padding: 10,
                    style: '{\n    font-weight:bold\n}',
                    text: 'Select Type of Classified(s):'
                },
                {
                    xtype: 'checkboxgroup',
                    flex: 1,
                    margin: '0 0 0 10',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    fieldLabel: 'Residents',
                    labelStyle: 'text-decoration:underline',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Selling an item (e.g. my grand piano, furniture, \'96 Corolla)'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Posting a job (e.g. need help with yard work, shovelling snow, babysitting)'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Youth classifieds (e.g. looking for work: tutoring, raking leaves, pet-walking after school)'
                        }
                    ]
                },
                {
                    xtype: 'checkboxgroup',
                    flex: 1,
                    margin: '0 0 0 10',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    fieldLabel: 'Businesses',
                    labelStyle: 'text-decoration:underline',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Posting a job for teens (14+)'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Posting a job for teens (18+)'
                        }
                    ]
                },
                {
                    xtype: 'label',
                    flex: 1,
                    html: '<div class=\'message_box\'>For Free Classifieds, listings must be 40 words or less and  must not be business-related, except for youth offering services. Youth classifieds will be confirmed with a call to receive parental permission to run the ad. All ad submissions will receive email confirmation. Please see your newsletter for deadline information.</div>',
                    margin: '0 10'
                },
                {
                    xtype: 'textareafield',
                    flex: 1,
                    height: 140,
                    itemId: 'classified_text',
                    margin: 10,
                    padding: '0 10',
                    fieldLabel: 'Classified Ad(s)'
                }
            ]
        });

        me.callParent(arguments);
    }

});