/*
 * File: app/view/OtherContent.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SubmitContent.view.OtherContent', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.otherContent',

    itemId: 'othercontentpanel',
    autoDestroy: false,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'All other Content & Photos',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: {
                labelAlign: 'top',
                padding: 10
            },
            items: [
                {
                    xtype: 'combobox',
                    flex: 1,
                    itemId: 'class_publication_id',
                    fieldLabel: 'Choose Your Publication',
                    labelStyle: 'font-weight:bold',
                    emptyText: 'Select a Publication...'
                },
                {
                    xtype: 'label',
                    flex: 1,
                    margin: '0 10',
                    padding: 10,
                    style: '{\n    font-weight:bold\n}',
                    text: 'Select Type of Classified(s):'
                },
                {
                    xtype: 'fieldcontainer',
                    flex: 1,
                    height: 120,
                    width: 400,
                    defaults: {
                        labelAlign: 'top',
                        padding: 10
                    },
                    layout: {
                        type: 'column'
                    },
                    items: [
                        {
                            xtype: 'checkboxgroup',
                            columnWidth: 0.5,
                            margin: '0 0 0 10',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            fieldLabel: 'Resident Features',
                            labelStyle: 'text-decoration:underline',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'Business Feature'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'Family Feature'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'Pet Feature'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'Welcome to the Neighborhood Feature'
                                }
                            ]
                        },
                        {
                            xtype: 'checkboxgroup',
                            columnWidth: 0.5,
                            margin: '0 0 0 10',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            fieldLabel: 'Homeowner Association',
                            labelStyle: 'text-decoration:underline',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'President & Committee Letters'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'News & Special Dates/Events'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'Important Notices & Covenant Reminders'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'checkboxgroup',
                    flex: 1,
                    margin: '0 0 0 10',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    fieldLabel: 'Other Article, Photos or Postings Submissions',
                    labelStyle: 'text-decoration:underline',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Vacation, Wedding Photos & Announcements'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Subdivision Groups: Book Club, Bunko, Women\'s Group, etc.'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Events: School, Charities, Community & Organizations'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Accomplishments: School, Sports & Extracurricular Activities'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Miscellaneous'
                        }
                    ]
                },
                {
                    xtype: 'label',
                    flex: 1,
                    hidden: true,
                    html: '<div class=\'message_box\'>NOTE: Added your file(s) first by clicking on the \'Add\' button.  Then select your file to upload. Repeat for each file you wish to submit. Finally, when you\'ve added all your file(s), click on the \'Upload\' button to send your file(s) to Neighborhood Communications.</div>',
                    margin: '0 10'
                },
                {
                    xtype: 'filefield',
                    flex: 1,
                    fieldLabel: 'Upload File'
                },
                {
                    xtype: 'textareafield',
                    flex: 1,
                    height: 140,
                    itemId: 'special_instructions',
                    margin: 10,
                    padding: '0 10',
                    fieldLabel: 'Special Instructions'
                }
            ]
        });

        me.callParent(arguments);
    }

});