/*
 * File: app/model/Contract.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.model.Contract', {
    extend: 'Ext.data.Model',
    alias: 'model.contract',

    uses: [
        'JavisERP.model.Client',
        'JavisERP.model.PaymentType',
        'JavisERP.model.Advertisement'
    ],

    idProperty: 'id',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'contract_number'
        },
        {
            name: 'client_name',
            mapping: 'client.name'
        },
        {
            name: 'total_sales',
            type: 'float'
        },
        {
            name: 'discount'
        },
        {
            name: 'subtotal'
        },
        {
            name: 'first_month_payment',
            type: 'float'
        },
        {
            name: 'monthly_payment',
            type: 'float'
        },
        {
            name: 'payment_type_id',
            mapping: 'payment_type.name'
        },
        {
            name: 'sale_date',
            type: 'date'
        }
    ],

    hasOne: [
        {
            associationKey: 'id',
            model: 'JavisERP.model.Client',
            foreignKey: 'client_id'
        },
        {
            associationKey: 'id',
            model: 'JavisERP.model.PaymentType',
            foreignKey: 'payment_type_id'
        }
    ],

    hasMany: {
        associationKey: 'id',
        model: 'JavisERP.model.Advertisement',
        primaryKey: 'advertisement',
        foreignKey: 'advertisement_id',
        name: 'advertisements'
    },

    proxy: {
        type: 'ajax',
        api: '//http://docs.sencha.com/ext-js/4-1/#!/api/Ext.data.proxy.Server-cfg-api\ncreate: \'/server/web/index.php/contract/new\',\nread: \'/server/web/index.php/contract/load\',\nupdate: \'/server/web/index.php/contract/update\',\ndestory: \'/server/web/index.php/contract/delete\'',
        url: 'resources/js/contract.json',
        reader: {
            type: 'json',
            idProperty: 'id',
            root: 'contract',
            totalProperty: 'totalCount'
        }
    }
});